services:
  renfe-whisperlive-gpu-asr:
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu.services
    container_name: renfe-whisperlive-gpu-asr
    command: ["python", "run_server_api.py"]
    ports:
      - "${ASR_PORT}:${ASR_PORT}"
    networks:
      - whisper-net

  renfe-whisperlive-gpu-fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu.services
    container_name: renfe-whisperlive-gpu-fastapi
    command: ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "${FASTAPI_PORT}"]
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - renfe-whisperlive-gpu-asr
    networks:
      - whisper-net

networks:
  whisper-net:
    driver: bridge
