services:
  renfe-whisperlive-gpu:
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu.services
    container_name: renfe-whisperlive-gpu
    # command: bash -c "
    #   python3 run_server_api.py --port ${ASR_PORT} &
    #   fastapi dev main.py --host 0.0.0.0 --port ${FASTAPI_PORT}"
    ports:
      - "${ASR_PORT}:${ASR_PORT}"
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    networks:
      - whisper-net
    environment:
      ASR_SERVER: ${ASR_SERVER}
      ASR_PORT: ${ASR_PORT}
      ASR_MODEL: ${ASR_MODEL}
      ASR_LANGUAGE: ${ASR_LANGUAGE}
      ASR_MUTE_AUDIO_PLAYBACK: ${ASR_MUTE_AUDIO_PLAYBACK}
      FASTAPI_SERVER: ${FASTAPI_SERVER}
      FASTAPI_PORT: ${FASTAPI_PORT}
      KAFKA_SERVER: ${KAFKA_SERVER}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      DO_PRINT_KAFKA_MESSAGES: ${DO_PRINT_KAFKA_MESSAGES}
      DO_SEND_KAFKA_MESSAGES: ${DO_SEND_KAFKA_MESSAGES}

  # renfe-whisperlive-gpu-asr:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.gpu.services
  #   container_name: renfe-whisperlive-gpu-asr
  #   command: ["python", "run_server_api.py", "--port", "${ASR_PORT}"]
  #   ports:
  #     - "${ASR_PORT}:${ASR_PORT}"
  #   networks:
  #     - whisper-net
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # deploy:
    #   replicas: 1  # Set to desired count for scaling
    #   resources:
    #     reservations:
    #       generic_resources:
    #         - discrete_resource_spec:
    #             kind: 'NVIDIA-GPU'
    #             value: 1
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['0']
    #         capabilities: [gpu]

  # renfe-whisperlive-gpu-fastapi:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.gpu.services
  #   container_name: renfe-whisperlive-gpu-fastapi
  #   command: ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "${FASTAPI_PORT}"]
  #   ports:
  #     - "${FASTAPI_PORT}:${FASTAPI_PORT}"
  #   depends_on:
  #     - renfe-whisperlive-gpu-asr
  #   networks:
  #     - whisper-net
  #   environment:
  #     ASR_SERVER: ${ASR_SERVER}
  #     ASR_PORT: ${ASR_PORT}
  #     ASR_MODEL: ${ASR_MODEL}
  #     ASR_LANGUAGE: ${ASR_LANGUAGE}
  #     ASR_MUTE_AUDIO_PLAYBACK: ${ASR_MUTE_AUDIO_PLAYBACK}

networks:
  whisper-net:
    driver: bridge
