services:
  renfe-whisperlive-gpu-asr:
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu.services
    container_name: renfe-whisperlive-gpu-asr
    command: ["python", "run_server_api.py"]
    ports:
      - "9090:9090"
    networks:
      - whisper-net

  renfe-whisperlive-gpu-fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu.services
    container_name: renfe-whisperlive-gpu-fastapi
    command: ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "8050"]
    ports:
      - "8050:8050"
    depends_on:
      - renfe-whisperlive-gpu-asr
    networks:
      - whisper-net

networks:
  whisper-net:
    driver: bridge
