---
data:
  file_list: /home/mumbert/Documentos/BSC/projects/langtech-bsc/WhisperLive/evaluation/file_lists/test.txt
metrics:
  error: ["wer"]
  metadata: ["duration"]
models: ["large-v2"]
steps:                              # in order to control what is done in the current execution
  do_full_file_transcription: false
  do_real_time_transcription: true
  do_compute_metrics: false
  do_plots: false
output:
  folder: evaluation/results/