FROM python:3.10-bookworm

ARG DEBIAN_FRONTEND=noninteractive

# install lib required for pyaudio
RUN apt update && \
    apt install -y -no-install-recommends \
    alsa-utils alsa-oss libasound2 libasound2-dev \
    portaudio19-dev python3-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# update pip to support for whl.metadata -> less downloading
RUN pip install --no-cache-dir -U "pip>=24"

# create a working directory
# RUN mkdir /app
WORKDIR /app

# install the requirements for running the whisper-live server
COPY requirements/server.txt /app/
RUN pip install --no-cache-dir -r server.txt && rm server.txt

# install the requirements for running the whisper-live client
COPY requirements/client.txt /app/
RUN pip install --no-cache-dir -r client.txt && rm client.txt

# make the paths of the nvidia libs installed as wheels visible. equivalent to:
# export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
ENV LD_LIBRARY_PATH="/usr/local/lib/python3.10/site-packages/nvidia/cublas/lib:/usr/local/lib/python3.10/site-packages/nvidia/cudnn/lib"

COPY whisper_live /app/whisper_live
COPY run_server.py /app

EXPOSE 9090/tcp
EXPOSE 8050/tcp

COPY scripts/entrypoint_docker.sh entrypoint_docker.sh
RUN chmod +x entrypoint_docker.sh
COPY app/main.py /app

RUN mkdir -p /examples/client
COPY examples/ /examples/

#CMD ["python", "run_server.py"]
# CMD ["/bin/bash", "-c", "python run_server.py && fastapi dev app/main.py --port 8050"]
CMD ["bash",  "entrypoint_docker.sh"]