INFERENCE_ENDPOINT_NAME: "renfe-whisperlive-gpu"
NAMESPACE: "langtech-innovation"
REPOSITOY: "openai/whisper-tiny"
FRAMEWORK: "pytorch"
TASK: "custom"
ACCELERATOR: "gpu"
VENDOR: "aws"
REGION: "us-east-1"
TYPE: "PUBlIC"
INSTANCE_SIZE: "x1"
INSTANCE_TYPE: "nvidia-t4"
CUSTOM_IMAGE_URL: "registry.gitlab.bsc.es/lang-tech-unit/innovation/renfe/mvp/whisperlive-renfe-whisperlive-gpu:v1.0.0"

